apiVersion: apps/v1 
kind: Deployment
metadata:
  name: mysql
spec:
  minReadySeconds: 55
  progressDeadlineSeconds: 60
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        ports:
        - containerPort: 3306
          name: mysql
        