apiVersion: apps/v1
kind: Deployment
metadata:
  name: komunikator-deployment-canary
  labels:
    app: komunikator
    version: "2.0"
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 3
      maxSurge: 20%
  replicas: 8
  selector:
    matchLabels:
      app: komunikator
  template:
    metadata:
      labels:
        app: komunikator
    spec:
      containers:
        - name: komunikator
          image: secopstech/socket-io-chat:latest
          ports:
            - containerPort: 80
