apiVersion: apps/v1
kind: Deployment
metadata:
  name: komunikator-deployment2-canary
  labels:
    app: komunikator3
    version: "2.0"
spec:
  replicas: 8
  selector:
    matchLabels:
      app: komunikator3
  template:
    metadata:
      labels:
        app: komunikator3
    spec:
      containers:
      - name: komunikator3
        image: jjchmielewski/lab10
        ports:
        - containerPort: 8080