version: "3.7"
      
services:
  db:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
  msg_server:
    build:
      context: .
      dockerfile: Dockerfile
    image: build-agent
    container_name: msg_server
    depends_on:
      - db
  test:
    build:
      context: ./test
      dockerfile: Dockerfile
    image: test-agent
    container_name: msg_client
    ports:
      - "8080:8081"
    depends_on:
      - msg_server