apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 3
  selector:  
    matchLabels:
      app: rest-api
      version: "v1"
  template:
    metadata:
      name: api-pod
      labels:   
        app: rest-api
        version: "v1"
    spec: 
      containers:
      - name: api
        image: dawrr756hj23/spring-boot-api:1.0.0

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-canary-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-api
      version: "v2"
  template:
    metadata:
      name: api-pod
      labels:
        app: rest-api
        version: "v2"
    spec:
      containers:
      - name: api
        image: dawrr756hj23/spring-boot-api:1.0.1

---

apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: rest-api
  ports:
  - port: 80
    targetPort: 8080
