
apiVersion: apps/v1
kind: Deployment
metadata:
  name: komunikator-deployment-recreate
  labels:
    app: komunikator
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: komunikator
  template:
    metadata:
      labels:
        app: komunikator
    spec:
      containers:
      - name: komunikator
        image: aleksanderfilek/wireappweb:1.1
        ports:
        - containerPort: 8080 