
apiVersion: apps/v1
kind: Deployment
metadata:
  name: komunikator-deployment-rollingupdate
  labels:
    app: komunikator
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      app: komunikator
  template:
    metadata:
      labels:
        app: komunikator
    spec:
      containers:
      - name: komunikator
        image: aleksanderfilek/wireappweb:1.1
        ports:
        - containerPort: 8080 