apiVersion: apps/v1
kind: Deployment
metadata:
  name: komunikator-deployment-canary-v2
  labels:
    app: komunikator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: komunikator
      version: v2.0.0
  template:
    metadata:
      labels:
        app: komunikator
        version: v2.0.0
    spec:
      containers:
      - name: komunikator
        image: aleksanderfilek/wireappweb:1.1
        ports:
        - containerPort: 8080 