apiVersion: v1
kind: Service
metadata:
  name: komunikator
  labels:
    app: komunikator
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: komunikator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: komunikator-deployment-canary-v1
  labels:
    app: komunikator
spec:
  replicas: 10
  selector:
    matchLabels:
      app: komunikator
      version: v1.0.0
  template:
    metadata:
      labels:
        app: komunikator
        version: v1.0.0
    spec:
      containers:
      - name: komunikator
        image: aleksanderfilek/wireappweb:1.0
        ports:
        - containerPort: 8080 