apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dep3
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
        version: v1.2.2
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80