apiVersion: apps/v1
kind: Deployment
metadata:
  name: komunikator-deployment-canary
  labels:
    app: komunikator
    version: "2.0"
spec:
  replicas: 8
  selector:
    matchLabels:
      app: komunikator
  template:
    metadata:
      labels:
        app: komunikator
    spec:
      containers:
      - name: komunikator
        image: adriandabrowski/web-app-lab-9:1.0.1
        ports:
        - containerPort: 3030
