apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc
spec:
  minReadySeconds: 55
  progressDeadlineSeconds: 60
  replicas: 2
  selector:
    matchLabels:
      app: mc
  template:
    metadata:
      labels:
        app: mc
    spec:
      containers:
      - name: mc
        image: itzg/minecraft-server:2022.3.0
        ports:
        - containerPort: 25565