apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2022-06-12T23:03:35Z"
  labels:
    app: simple-tetris
  name: simple-tetris
  namespace: default
  resourceVersion: "12444"
  uid: b7709051-1a72-4bcc-91cf-cec0b851b8a9
spec:
  replicas: 2
  containers:
  - image: simple-tetris:jedyny-sluszny
    imagePullPolicy: IfNotPresent
    name: simple-tetris
    ports:
    - containerPort: 8080
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-5tlsp
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: minikube
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-5tlsp
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-06-12T23:03:35Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2022-06-12T23:03:37Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2022-06-12T23:03:37Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2022-06-12T23:03:35Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://e3cabcd7d9478f614d8bb98a4d8550ab3ac77d63d694f07e4ccdfd068a14e900
    image: simple-tetris-deploy:latest
    imageID: docker://sha256:dc93246101487eecff85adaf02e4229047c77721603f699971324a13641e3bc2
    lastState: {}
    name: simple-tetris
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2022-06-12T23:03:36Z"
  hostIP: 192.168.49.2
  phase: Running
  podIP: 172.17.0.5
  podIPs:
  - ip: 172.17.0.5
  qosClass: BestEffort
  startTime: "2022-06-12T23:03:35Z"
