apiVersion: apps/v1
kind: Deployment
metadata:
  name: komunikator
spec:
  replicas: 8
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: komunikator
  template:
    metadata:
      labels:
        app: komunikator
        track: stable
    spec:
      containers:
      - name: komunikator
        image: mnichmaciej/cicd:0.79
        ports:
        - containerPort: 8080