apiVersion: apps/v1
kind: Deployment
metadata:
  name: komunikator-deployment
  labels:
    app: komunikator2
spec:
  replicas: 4
  selector:
    matchLabels:
      app: komunikator2
  template:
    metadata:
      labels:
        app: komunikator2
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80