apiVersion: apps/v1
kind: Deployment
metadata:
  name: komunikator-deployment
  labels:
    app: komunikator
spec:
  replicas: 8
  selector:
    matchLabels:
      app: komunikator
  template:
    metadata:
      labels:
        app: komunikator
    spec:
      containers:
      - name: komunikator
        image: mcmkos/deltachat-desktop:Lab10_Versionn
        ports:
        - containerPort: 80
      restartPolicy: Always
      
      





