apiVersion: apps/v1
kind: Deployment
metadata:
  name: komunikator-deployment-recreate
  labels:
    app: komunikator2
spec:
  replicas: 4
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: komunikator2
  template:
    metadata:
      labels:
        app: komunikator2
    spec:
      containers:
      - name: komunikator2
        image: annaczesak/lab10
        ports:
        - containerPort: 9999