apiVersion: apps/v1
kind: Deployment
metadata:
  name: komunikator-deployment
  labels:
    app: komunikator3
spec:
  replicas: 8
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: komunikator3
  template:
    metadata:
      labels:
        app: komunikator3
    spec:
      containers:
      - name: nginx
        image: ngnx:1.14.2
        ports:
        - containerPort: 80