apiVersion: apps/v1
kind: Deployment
metadata:
  name: komunikator-deployment2
  labels:
    app: komunikator2
spec:
  replicas: 8
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: komunikator2
  template:
    metadata:
      labels:
        app: komunikator2
    spec:
      containers:
      - name: komunikator3
        image: jjchmielewski/lab10
        ports:
        - containerPort: 8080