apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg
spec:
  minReadySeconds: 55
  progressDeadlineSeconds: 60
  selector:
    matchLabels:
      app: mypostgres
  replicas: 4 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: mypostgres
    spec:
      containers:
      - name: pg
        image: postgres
        ports:
        - containerPort: 5432