version: "3.9"
services:
  b_agent:
    build:
      context: "./buildAgent"
      dockerfile: "dockerfile"
    working_dir: /app
    volumes:
      - ./.docker:/app

  t_agent:
    build:
      context: "./testAgent"
      dockerfile: "dockerfile"
    working_dir: /app
    volumes:
      - ./.docker:/app
      - ./testagent:/test