version: "3.3"
services:
    buildsection:
        image: build-agent:latest
        build:
            context: .
            dockerfile: ./Dockerfile_deltachat_build
    testsection:
        image: test-agent:latest
        build:
            context: .
            dockerfile: ./Dockerfile_deltachat_test
        depends_on:
            - buildsection