version: "3.9"
services:
  b_agent:
    build:
      context: "./build-agent"
      dockerfile: "Dockerfile"
    working_dir: /app
    volumes:
      - ./.docker:/app
    
  t_agent:
    build:
      context: "./test-agent"
      dockerfile: "Dockerfile"
    working_dir: /app
    volumes:
      - ./.docker:/app
      - ./test_agent:/test