apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx-deployment
  template:
    metadata:
      labels:
        app: nginx-deployment
        version: "1.0"
    spec:
      containers:
      - name: nginx-dep
        image: nginx
        ports:
        - containerPort: 80
