apiVersion: apps/v1
kind: Deployment
metadata:
  name: deltachat-deployment
  labels:
    app: deltachat
spec:
  replicas: 4
  selector:
    matchLabels:
      app: deltachat
  template:
    metadata:
      labels:
        app: deltachat
    spec:
      containers:
      - name: deltachat
        image: piotrekapriasz/build-agent:latest
        ports:
        - containerPort: 80
      restartPolicy: OnFailure