apiVersion: v1
kind: Pod
metadata:
  name: java-app
  labels:
    app: test
spec:
  containers:
    - name: myapp
      image: myapp
      imagePullPolicy: Never
      ports:
      - containerPort: 8080
