apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
  labels:
    app: test
spec:
  replicas: 0
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: myapp
          image: myapp
          imagePullPolicy: Never
          ports:
          - containerPort: 8080
