apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc
spec:
  minReadySeconds: 55
  progressDeadlineSeconds: 60
  replicas: 4
  selector:
    matchLabels:
      app: mc
  template:
    metadata:
      labels:
        app: mc
    spec:
      containers:
      - name: mc
        image: itzg/minecraft-server:2022.4.1
        ports:
        - containerPort: 25565
        env:
          - name: EULA
            value: "TRUE"
