apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mc
  template:
    metadata:
      labels:
        app: mc
        version: "1.0"
    spec:
      containers:
      - name: mc
        image: itzg/minecraft-server
        ports:
        - containerPort: 25565
        env:
          - name: EULA
            value: "TRUE"
