version: '3.9'
services:
  deltachat-build:
    build: 
      context: .
      dockerfile: ./buildAgent/Dockerfile
  deltachat-test:
    build:
      context: .
      dockerfile: ./testAgent/Dockerfile
    depends_on:
    - deltachat-build
