apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: todoapp-namespace
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 4
  selector:
    matchLabels:
      io.kompose.service: backend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: backend
        version: "3.0"
    spec:
      containers:
        - env:
            - name: network_mode
              value: host
          image: sebastian99kul/backendtodoapp:1.0.1
          name: backend-go-todoapp
          ports:
            - containerPort: 8000
          resources: {}
      restartPolicy: Always
status: {}
