version: "3.9"
services:
  build_agent:
    build:
      context: "./build agent"
      dockerfile: "Dockerfile"
    volumes:
      - ./.docker:/app

  test_agent:
    build:
      context: "./test agent"
      dockerfile: "Dockerfile"
    volumes:
      - ./.docker:/app
      - ./testagent:/test