apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-httpd.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: httpd
  name: httpd
spec:
  replicas: 4
  selector:
    matchLabels:
      io.kompose.service: httpd
  strategy:
    type: RollingUpdate
    rollingUpdate:
     maxSurge: 1
     maxUnavailable: 0
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-httpd.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: httpd
    spec:
      containers:
        - image: httpd:latest
          name: httpd
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
