apiVersion: v1
kind: Pod
metadata:
  name: express
  labels:
    app: express
spec:
  containers:
    - name: express
      image: nodejs_app
      imagePullPolicy: Never
      ports:
      - containerPort: 3200
