apiVersion: apps/v1
kind: Deployment
metadata:
  name: lz4web-deployment
spec:
  selector:
    matchLabels:
      app: lz4web
  replicas: 3
  template:
    metadata:
      labels:
        app: lz4web
    spec:
      containers:
        - name: nginx
          image: lz4web:1.0
          ports:
            - containerPort: 8000
