
version: '3.9'
services:
    build-agent:
      image: build-agent:latest
      build: 
        context: .
        dockerfile: ./Build-Agent/Dockerfile
    test-agent:
      image: test-agent:latest
      build:
        context: .
        dockerfile: ./Test-Agent/Dockerfile
      depends_on:
        - build-agent