apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  labels:
    app: todo-app-2
spec:
  replicas: 5
  selector:
    matchLabels:
      app: todo-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: todo-app
        version: "5"
    spec:
      containers:
      - name: todo-app
        image: 4202137/todo:modified
        ports:
        - containerPort: 8080