apiVersion: apps/v1
kind: Deployment
metadata:
  name: jp-nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: jp_blad_nginx
        imagePullPolicy: Never
        ports:
        - containerPort: 2222
